# Generated by Django 4.0.5 on 2022-12-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_cars_deliveryclassifier_hellotask_income_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': False, 'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
    ]
